<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.svenruppert</groupId>
        <artifactId>dependencies</artifactId>
        <version>06.00.03</version>
    </parent>

    <groupId>com.svenruppert.junit5</groupId>
    <artifactId>main</artifactId>
    <version>00.00.01-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
<!--        <module>00_basics</module>-->
        <module>module_01</module>
        <module>module_01_examples</module>
        <module>module_02</module>
        <module>module_02_examples</module>
        <module>module_03</module>
        <module>module_03_examples</module>
        <module>module_04</module>
    </modules>

    <properties>
        <deploy-repo-url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</deploy-repo-url>
        <deploy-repo-snapshots-url>https://s01.oss.sonatype.org/content/repositories/snapshots
        </deploy-repo-snapshots-url>

        <jdk.version>21</jdk.version>

        <maven.compiler.release>${jdk.version}</maven.compiler.release>
        <maven.compiler.source>${jdk.version}</maven.compiler.source> <!--redundant, but IntelliJ doesn't-->
        <maven.compiler.target>${jdk.version}</maven.compiler.target> <!--use release when importing-->

        <maven.compiler.testRelease>${jdk.version}</maven.compiler.testRelease>
        <maven.compiler.testSource>${jdk.version}</maven.compiler.testSource>
        <maven.compiler.testTarget>${jdk.version}</maven.compiler.testTarget>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <!--TDD jUnit5-->
        <junit-platform-maven-plugin.timeout>300</junit-platform-maven-plugin.timeout>

        <pitest-prod-classes>com.svenruppert.junit5.*</pitest-prod-classes>
        <pitest-test-classes>junit.*</pitest-test-classes>
    </properties>


    <organization>
        <name>Sven Ruppert</name>
        <url>http://www.svenruppert.com</url>
    </organization>

    <url>https://github.com/svenruppert/JUnit5Course</url>
    <name>JUnit5 Course</name>
    <description>The beginning of your OSS project</description>
    <scm>
        <url>https://github.com/svenruppert/JUnit5Course</url>
        <connection>scm:git:https://github.com/svenruppert/JUnit5Course.git</connection>
        <developerConnection>scm:git:https://github.com/svenruppert/JUnit5Course.git</developerConnection>
        <tag>HEAD</tag>
    </scm>
    <developers>
        <developer>
            <name>Sven Ruppert</name>
            <email>sven.ruppert@gmail.com</email>
            <roles>
                <role>Founder</role>
                <role>Developer</role>
            </roles>
            <timezone>+1</timezone>
        </developer>
    </developers>
    <issueManagement>
        <system>GitHub</system>
        <url>https://github.com/svenruppert/JUnit5Course/issues</url>
    </issueManagement>
    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
            <comments>A business-friendly OSS license</comments>
        </license>
    </licenses>

    <dependencies>
        <!--jUnit5-->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- Only required to run tests in an IDE that bundles an older version -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-testkit</artifactId>
            <scope>test</scope>
        </dependency>

        <!--    Logging-->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
        </dependency>

<!--        For the examples-->
        <dependency>
            <groupId>com.svenruppert</groupId>
            <artifactId>core</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!--Enable mutation testing-->
            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-junit5-plugin</artifactId>
                        <version>1.2.1</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <threads>4</threads>
                    <outputFormats>
                        <outputFormat>XML</outputFormat>
                        <outputFormat>HTML</outputFormat>
                    </outputFormats>
                    <targetClasses>
                        <param>${pitest-prod-classes}</param>
                    </targetClasses>
                    <targetTests>
                        <param>${pitest-test-classes}</param>
                    </targetTests>
                </configuration>
            </plugin>
<!--            If you want to skip this module-->
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-checkstyle-plugin</artifactId>-->
<!--                <configuration>-->
<!--                    <skip>true</skip>-->
<!--                </configuration>-->
<!--            </plugin>-->
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-surefire-plugin</artifactId>-->
<!--            </plugin>-->
        </plugins>
    </build>
</project>